apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo
  namespace: argocd
spec:
  project: default
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  source:
    chart: argo
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 0.13.8
    helm:
      values: |-
        server:
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
            hosts:
              - argo.test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
