apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  destination:
    namespace: minio
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/myspotontheweb/k8s-platform.git
    path: charts/minio
    helm:
      values: |-
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
          hosts:
          - minio.test
        accessKey: XXXXXXXXXX
        secretKey: YYYYYYYYYY
        buckets:
        - name: repo1
          policy: none
          purge: false
        - name: repo2
          policy: none
          purge: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
